# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Rice_U_folder/2024Fall/capstone/eth_pdm_mic_full/eth_pdm_mic/eth_pdm_mic.srcs/sources_1/ip/cic_compiler_0/cic_compiler_0.xci
# IP: The module: 'cic_compiler_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Rice_U_folder/2024Fall/capstone/eth_pdm_mic_full/eth_pdm_mic/eth_pdm_mic.gen/sources_1/ip/cic_compiler_0/cic_compiler_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cic_compiler_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: e:/Rice_U_folder/2024Fall/capstone/eth_pdm_mic_full/eth_pdm_mic/eth_pdm_mic.srcs/sources_1/ip/cic_compiler_0/cic_compiler_0.xci
# IP: The module: 'cic_compiler_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Rice_U_folder/2024Fall/capstone/eth_pdm_mic_full/eth_pdm_mic/eth_pdm_mic.gen/sources_1/ip/cic_compiler_0/cic_compiler_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cic_compiler_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
